version: '3'
services:
  app:
    build: .
    env_file: .env
    networks:
      marine-tts:
        ipv4_address: 172.0.0.10
    restart: always
  voicevox:
    image: aoirint/voicevox_engine:cpu-latest
    ports:
      - "50021:50021"
    networks:
      marine-tts:
        ipv4_address: 172.0.0.11
    restart: always

networks:
  marine-tts:
    ipam:
      driver: default
      config:
        - subnet: 172.0.0.0/24
