version: '3'
services:
  marine-tts:
    build: .
    env_file: marine-tts.env
    networks:
      marine-tts:
        ipv4_address: 172.16.0.10
    restart: always
  voicevox:
    build: ./voicevox_engine
    networks:
      marine-tts:
        ipv4_address: 172.16.0.11
    restart: always
    environment:
      - BASE_IMAGE=ubuntu:focal
      - BASE_RUNTIME_IMAGE=ubuntu:focal
      - VOICEVOX_CORE_LIBRARY_NAME=core_cpu
      - LIBTORCH_URL=https://download.pytorch.org/libtorch/cpu/libtorch-cxx11-abi-shared-with-deps-1.9.0%2Bcpu.zip
      
networks:
  marine-tts:
    ipam:
      driver: default
      config:
        - subnet: 172.16.0.0/16
